### ISSUE TITLE
OpenAPIドキュメントの更新

### ISSUE THREAD

**Issue by itoshot** [Personal-Data-Linkage-Module/pxr-operator-service#17]
```[tasklist]
### Tasks
- [ ] POST /
- [ ] PUT /{operatorId}
- [ ] DELETE /{operatorId}
- [ ] GET /
- [ ] GET /{operatorId}
- [ ] POST /login
- [ ] POST /ind/login
- [ ] POST /login/sso
- [ ] POST /login/onetime
- [ ] POST /logout
- [ ] POST /ind/logout
- [ ] POST /session
- [ ] POST /ind/session
- [ ] PUT /password/{operatorId}
- [ ] POST /ind/login/onetime
- [ ] POST /ind/identifyCode
- [ ] POST /user/info
- [ ] DELETE /user/info
- [ ] PUT /ind/user/info
- [ ] GET /user/info
- [ ] GET /ind/user/info
- [ ] POST /user/info/list
- [ ] POST /user/info/search
- [ ] POST /ind/sms-verificate
- [ ] POST /ind/sms-verificate/verify
```
